### ISSUE TITLE
Getting JSON ERROR: "Syntax error" when calling getProducts API

### ISSUE THREAD

**Issue by korzonkiee** [woosignal/flutter-woocommerce-api#10]
## Steps to reproduce
1. Clone the repository.
2. Rename `woosignalWoocommerceExample` to `main`. Without that change, the app won't run.
    
    <img width="876" alt="CleanShot 2022-10-09 at 13 29 22@2x" src="https://user-images.githubusercontent.com/26259846/194751788-33d2a8c5-3354-4537-8263-f1b730dbc8e1.png">

3. Set the API key.
4. Set debug mode to see errors in the console:

    ![CleanShot 2022-10-09 at 13 31 01@2x](https://user-images.githubusercontent.com/26259846/194751835-7d11ce7e-3e7b-4184-91aa-cafe37ca0622.png)

5. Run the example app.
6. Tap on the bulb button to get products from WooCommerce.
7. Observe the errors in the "Debug console" tab.

    <img width="853" alt="CleanShot 2022-10-09 at 13 32 29@2x" src="https://user-images.githubusercontent.com/26259846/194751910-df1b8097-ce43-4dd7-9a24-91ecbff95d13.png">

**Comment by korzonkiee** [comment]
Here is a little bit more information about the request/response. I hope it would be helpful 😄 

<img width="352" alt="CleanShot 2022-10-09 at 13 36 26@2x" src="https://user-images.githubusercontent.com/26259846/194752065-8340b6ea-d868-4f29-a4f4-b824356c4fbd.png">

**Comment by korzonkiee** [comment]
Environment:
- Wordpress version 6.0.2
- WooCommerce plugin version: 6.9.4

**Comment by korzonkiee** [comment]
Seems like it's unrelated to the `getProducts` call. I'm also getting the same error when calling other endpoints, e.g.:
- `getProductCategories` or
- `retrieveApiData`.

**Comment by agordn52** [comment]
Hi, hope you’re well.

This error happens when there’s an issue on the WordPress side.
Contact support here https://woosignal.com/support

Thanks, Anthony
