### ISSUE TITLE
Using other domain

### ISSUE THREAD

**Issue by jpearll** [woosignal/flutter-woocommerce-api#13]
Hi, is this package only restricted on using WooSignal sites? Can I configure it to use my own hosted Woo Commerce store?

**Comment by agordn52** [comment]
Hi @jpearll,

This package uses WooSignal to link your WooCommerce Store.
After you've linked your store you'll obtain an API key which you'll need to use this library.

Check out the docs [here](https://woosignal.com/docs/api/1.0/overview) to learn more.
