### ISSUE TITLE
Unsupported Platform (Web)

### ISSUE THREAD

**Issue by jpearll** [woosignal/flutter-woocommerce-api#14]
Hi, when trying to compile and run on the Web (mostly for debugging purposes), the WooSignal.init(...) throws an error message of type 'Unsupported Platform'. I think it might be related to the ApiProvider.setDeviceMeta() function that uses Platform.isAndroid, etc.

I've made a quick test and replaced the 'Platform' library with 'UniveralPlatform' and it looks like it's working (at least on the Web). 

Any chance you could make it compatible with the Web? Or simply adjust the code as proposed? Thanks :)

```dart

import 'package:universal_platform/universal_platform.dart';
...

if (UniversalPlatform.isAndroid) {
...
} else if (UniversalPlatform.isIOS) { 
...
} else if (UniversalPlatform.isDesktopOrWeb) {
...
}
```

**Comment by agordn52** [comment]
Hi @jpearll,

Yeah, you're right! Currently, Web is unsupported.
I think there might be some cool use cases for the library on the web so we'll support the change in a future update.

Thanks,
